<a href="https://colab.research.google.com/github/nirvanK11/TELECOM-CUSTOMER-CHURN/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Predicting the payment method 

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

from imblearn.combine import SMOTEENN

from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, plot_roc_curve

In [ ]:
data2 = pd.read_csv('/content/Telco-Customer-Churn.csv')

In [ ]:
data_res = pd.read_csv("/content/clean_data (1).csv")

In [ ]:
data_res2 = data_res.astype(int)

In [ ]:
#data_res2.to_csv("clean_data1.csv", index = False )

In [ ]:
data_res2

gender  SeniorCitizen  Partner  ...  MonthlyCharges  TotalCharges  Churn
0           0              0        1  ...               0             0      0
1           1              0        0  ...               0             0      0
2           1              0        0  ...               0             0      1
3           1              0        0  ...               0             0      0
4           0              0        0  ...               0             0      1
...       ...            ...      ...  ...             ...           ...    ...
10321       0              0        0  ...               0             0      1
10322       1              0        0  ...               0             0      1
10323       0              0        0  ...               0             0      1
10324       0              0        0  ...               0             0      1
10325       0              0        0  ...               0             0      1

[10326 rows x 20 columns]

In [ ]:
X = data_res2.drop(['Churn','PaymentMethod'], axis = 1)
y = data_res2['PaymentMethod']

In [ ]:
X

gender  SeniorCitizen  ...  MonthlyCharges  TotalCharges
0           0              0  ...               0             0
1           1              0  ...               0             0
2           1              0  ...               0             0
3           1              0  ...               0             0
4           0              0  ...               0             0
...       ...            ...  ...             ...           ...
10321       0              0  ...               0             0
10322       1              0  ...               0             0
10323       0              0  ...               0             0
10324       0              0  ...               0             0
10325       0              0  ...               0             0

[10326 rows x 18 columns]

In [ ]:
y

0        2
1        3
2        3
3        0
4        2
        ..
10321    2
10322    1
10323    2
10324    3
10325    3
Name: PaymentMethod, Length: 10326, dtype: int64

In [ ]:
smn = SMOTEENN(random_state = 5)

# Creating sample data
X, y = smn.fit_resample(X, y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 1)


In [ ]:
print('Shape of training data :', X_train.shape)

print('\nShape of testing data :', X_test.shape)

Shape of training data : (3801, 18)

Shape of testing data : (1629, 18)


Predecting which payment will the customer using 

In [ ]:
log = LogisticRegression(solver = 'newton-cg')

# Train the model
log.fit(X_train, y_train)

# Predict on test data
log_pred = log.predict(X_test)

print('Test Accuracy: {} %'.format(log.score(X_test, y_test).round(3)*100))

Test Accuracy: 65.3 %


In [ ]:
print('Confusion Matrix:\n')
print(confusion_matrix(y_test, log_pred))

Confusion Matrix:

[[184 129  34  30]
 [106 250  55  48]
 [ 30   7 338  21]
 [ 16  60  29 292]]


In [ ]:
print(classification_report(y_test, log_pred))

              precision    recall  f1-score   support

           0       0.55      0.49      0.52       377
           1       0.56      0.54      0.55       459
           2       0.74      0.85      0.79       396
           3       0.75      0.74      0.74       397

    accuracy                           0.65      1629
   macro avg       0.65      0.66      0.65      1629
weighted avg       0.65      0.65      0.65      1629



In [ ]:
# Create a KNN object
knn = KNeighborsClassifier()

# Train the model
knn.fit(X_train, y_train)

# Predict on test data
knn_pred = knn.predict(X_test)

print('Test Accuracy: {} %'.format(knn.score(X_test, y_test).round(3)*100))

Test Accuracy: 89.9 %


In [ ]:
print('Confusion Matrix:')
print(confusion_matrix(y_test, knn_pred))

Confusion Matrix:
[[314  39   6  18]
 [ 30 408  11  10]
 [  8   8 379   1]
 [ 12  16   6 363]]


In [ ]:
print(classification_report(y_test, knn_pred))

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       377
           1       0.87      0.89      0.88       459
           2       0.94      0.96      0.95       396
           3       0.93      0.91      0.92       397

    accuracy                           0.90      1629
   macro avg       0.90      0.90      0.90      1629
weighted avg       0.90      0.90      0.90      1629



In [ ]:
svc = SVC()

# Train the model
svc.fit(X_train, y_train)

# Predict on test data
svc_pred = svc.predict(X_test)

print('Test Accuracy: {} %'.format(svc.score(X_test, y_test).round(3)*100))

Test Accuracy: 83.2 %


In [ ]:
 #Create a decision tree object
tree = DecisionTreeClassifier(criterion='gini', max_depth=6, min_samples_leaf=8)

# Train the model
tree.fit(X_train, y_train)

# Predict on test data
tree_pred = tree.predict(X_test)

print('Test Accuracy: {} %'.format(tree.score(X_test, y_test).round(3)*100))

Test Accuracy: 70.0 %


In [ ]:
# Create a random forest object
randm = RandomForestClassifier()

# Train the model
randm.fit(X_train, y_train)

# Predict on test data
randm_pred = randm.predict(X_test)

print('Test Accuracy: {} %'.format(randm.score(X_test, y_test).round(3)*100))

Test Accuracy: 97.2 %
